version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: db-server
    environment:
      - POSTGRES_PASSWORD=salasana
      - POSTGRES_USER=user
      - POSTGRES_DB=backend-db
    volumes:
      - ./database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    container_name: redis-server

  frontend:
    image: frontend-example
    ports:
      - 5000:5000
    container_name: frontend

  backend:
    image: backend-example
    ports:
      - 8000:8000
    container_name: backend
    environment:
      - REDIS=redis-server
      - REDIS_port=6379
      - DB_USERNAME=user
      - DB_PASSWORD=salasana
      - DB_NAME=backend-db
      - DB_HOST=db-server
    depends_on:
        - redis
        - db

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./curl-format.txt:/etc/curl-format.txt:ro
    depends_on:
      - backend
    command: [nginx-debug, '-g', 'daemon off;']
