version: '3.5'

services:
  frontend:
    build: frontend
    ports:
      - 3000:3000
    container_name: frontend

  backend:
    build: backend
    ports:
      - 8000:8000
    container_name: backend
    volumes:
      - ./model:/src/model

  training:
    build: training
    container_name: training
    volumes:
      - ./model:/src/model
      - ./imgs:/src/imgs
      - ./training/data:/src/data