version: '3.5'

services:
  db:
    image: postgres
    restart: always
    container_name: db-server
    environment:
      - POSTGRES_PASSWORD=salasana
      - POSTGRES_USER=user
      - POSTGRES_DB=backend-db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
    container_name: redis-server

  frontend:
    image: frontend-example
    ports:
      - 3457:5000
    container_name: frontend-example

  backend:
    image: backend-example
    ports:
      - 3456:8000
    container_name: backend-example
    environment:
      - REDIS=redis-server
      - REDIS_port=6379
      - DB_USERNAME=user
      - DB_PASSWORD=salasana
      - DB_NAME=backend-db
      - DB_HOST=db-server
      depends_on:
        - redis
        - db
